### ISSUE TITLE
me request returns HTTP 400 "Invalid version."

### ISSUE THREAD

**Issue by lostmsu** [microsoftgraph/msgraph-sample-blazor-clientside#94]
### Where did you get the code?

- [x] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

When I login with Microsoft personal account and the app tries to query my information, I receive HTTP 400 bad request

For `https://graph.microsoft.com/me?%24select=displayName,mail,mailboxSettings,userPrincipalName`:

```
{
  "error": {
      "code": "BadRequest",
      "message": "Invalid version.",
      "innerError": {
          "date": "2023-07-13T00:22:11",
          "request-id": "6fe204d7-5b75-4c36-8bf1-acaa8cd743da",
          "client-request-id": "6fe204d7-5b75-4c36-8bf1-acaa8cd743da"
      }
  }
}
```

### To Reproduce

1. Follow the setup instructions
1. Click on Sign In

### Expected behavior

User information is retrieved.

### Screenshots

![image](https://github.com/microsoftgraph/msgraph-sample-blazor-clientside/assets/239520/01b16f1d-2cf9-418a-a343-b5c8a12a072e)

### Desktop

- OS: Windows 11 22H2
- Browser: Edge
- Version: 114.0.1823.79

### Dependency versions

- Authentication library (MSAL, etc.) version: 7.0.9
- Graph library (Graph SDK, REST library, etc.) version: 5.18.0

**Comment by jasonjoh** [comment]
Update: It's not limited to personal accounts. The SDK is not including the version segment in the URL. This URL is wrong:

```
https://graph.microsoft.com/me?%24select=displayName,mail,mailboxSettings,userPrincipalName
```

Between the `graph.microsoft.com` and the `/me` should be a version segment, `/v1.0`. The correct URL should be:

```
https://graph.microsoft.com/v1.0/me?%24select=displayName,mail,mailboxSettings,userPrincipalName
```

This appears to be an issue with the SDK. I'm finding out more from the engineering team.

**Comment by jasonjoh** [comment]
Ok, so while they sort out this issue, here's a workaround. In GraphClientFactory.cs, change the line that creates the `requestAdapter` to:

```csharp
var requestAdapter = new HttpClientRequestAdapter(
    new BlazorAuthProvider(accessor), null, null, httpClient)
        {
            BaseUrl = "https://graph.microsoft.com/v1.0"
        };
```
